### ISSUE TITLE
How do i update or remove an item in the datatable

### ISSUE THREAD

**Issue by samuelg78** [ptmcg/littletable#3]
There is no example of how we can update or remove an item from the datatable. Are these 2 operations supported in littletable?

**Comment by ptmcg** [comment]
Thanks for trying out littletable, and posting this question.

They absolutely are supported!

If you know the index of the item, you can treat a Table just like it was a list and do `del table[index_of_item_to_delete]`.

You can remove items using the `Table.remove()` method, passing a single object to remove, or a sequence of objects (such as the result from calling `Table.where()`).

You can also remove an item using `pop()`, similar to the `pop()` method for lists.

You can find more detailed info in https://github.com/ptmcg/littletable/blob/master/how_to_use_littletable.md#removing-objects

**Comment by samuelg78** [comment]
Thanks for reply, i can remove item now but the item value cannot be updated. I am using remove and insert in replacement of update.

**Comment by cramatt** [comment]
Is there no way to update a record? is the workaround really to remove and re-add it with new values?

**Comment by ptmcg** [comment]
The first part of this question is up to you, and that is, did you store mutable items in the table? For instance, many of littletable's operations are most efficient if the contents are all NamedTuples - however, since these are tuples, their contents can't be updated. If this is the case, you are pretty much limited to remove+replace. 

If the objects in your table _are_ mutable, then you _might_ be able to modify them in-place. The primary sticking point with doing so would depend on whether you have defined any indexes (either plain or search) on the table. 

- If you haven't, then you should be able to modify the objects in-place with no issue.
- If there _are_ indexes, but the changes you are making to the object are in none of the indexed fields, then again, you should be able to update in-place.
- The catch comes if you want to change an indexed field. Unlike true databases, littletable does not intercept all interactions with its tables' contents. Say you have a table of customers indexed by zip code (outside the US, you might call this "postal code"). That index is kept as an associated dict that maps zip code values to matching objects. If you change the zip code in the object, this index becomes invalid.

Here is some sample code showing some of these effects (here the indexed field is "name"):
```python
import littletable as lt

data = """\
name,a,b,c
A,1,2,3
B,4,5,6
"""

tbl = lt.Table()
tbl.create_index("name")
tbl.csv_import(data)
print(list(tbl.all.name))

# change non-indexed field - works fine
tbl[1].a = 100
tbl.present()
tbl.by.name["B"].present()

# change indexed field - not so good
tbl[1].name = "C"
# index does not recognize new name value - returns empty table
tbl.by.name["C"].present()
# index still points to this record with name="B"
tbl.by.name["B"].present()

print(tbl.by.name.keys())

# can we just remove the record?
tbl.pop(1)
# really messed up now - modified the wrong index list
print(tbl.by.name.items())

# put things right again
tbl.drop_index("name")
tbl.create_index("name")
print(tbl.by.name.items())
```

Does that give you some more insight into the issue?

**Comment by ptmcg** [comment]
Btw, I'm happy to see that littletable is getting some use beyond just my own projects! Let me know if I can be of any other help.
